### ISSUE TITLE
A question ؟

### ISSUE THREAD

**Issue by O4dg** [daycat/clashcheck#1]
Does this tool check the extension of the proxies.txt file?

**Comment by daycat** [comment]
Should you wish, you may choose to redirect the input source to an .txt file. However, keep in mind that as of now, only clash configs are supported, and so if your txt file includes a clash config, it will be accepted.

**Comment by daycat** [comment]
If no further concerns revolves the usage I shall close this issue. However, feel free to revive this thread should similar issues arise in the future.
